{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-config
data:
{{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
